/// Generated by the Protocol Buffers 3.2.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 3.0.13
/// Source file "ChannelAvatarAdd.proto"
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct ChannelAvatarAddRoot {
    public static let `default` = ChannelAvatarAddRoot()
    public var extensionRegistry:ExtensionRegistry

    init() {
        extensionRegistry = ExtensionRegistry()
        registerAllExtensions(registry: extensionRegistry)
        RequestRoot.default.registerAllExtensions(registry: extensionRegistry)
        ResponseRoot.default.registerAllExtensions(registry: extensionRegistry)
        GlobalRoot.default.registerAllExtensions(registry: extensionRegistry)
    }
    public func registerAllExtensions(registry: ExtensionRegistry) {
    }
}

final public class IGPChannelAvatarAdd : GeneratedMessage {

    public static func == (lhs: IGPChannelAvatarAdd, rhs: IGPChannelAvatarAdd) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpRequest == rhs.hasIgpRequest) && (!lhs.hasIgpRequest || lhs.igpRequest == rhs.igpRequest)
        fieldCheck = fieldCheck && (lhs.hasIgpAttachment == rhs.hasIgpAttachment) && (!lhs.hasIgpAttachment || lhs.igpAttachment == rhs.igpAttachment)
        fieldCheck = fieldCheck && (lhs.hasIgpRoomId == rhs.hasIgpRoomId) && (!lhs.hasIgpRoomId || lhs.igpRoomId == rhs.igpRoomId)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpRequest:IGPRequest!
    public fileprivate(set) var hasIgpRequest:Bool = false
    public fileprivate(set) var igpAttachment:String = ""
    public fileprivate(set) var hasIgpAttachment:Bool = false

    public fileprivate(set) var igpRoomId:Int64 = Int64(0)
    public fileprivate(set) var hasIgpRoomId:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpRequest {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpRequest)
        }
        if hasIgpAttachment {
            try codedOutputStream.writeString(fieldNumber: 2, value:igpAttachment)
        }
        if hasIgpRoomId {
            try codedOutputStream.writeInt64(fieldNumber: 3, value:igpRoomId)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpRequest {
            if let varSizeigpRequest = igpRequest?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpRequest
            }
        }
        if hasIgpAttachment {
            serialize_size += igpAttachment.computeStringSize(fieldNumber: 2)
        }
        if hasIgpRoomId {
            serialize_size += igpRoomId.computeInt64Size(fieldNumber: 3)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPChannelAvatarAdd.Builder {
        return IGPChannelAvatarAdd.classBuilder() as! IGPChannelAvatarAdd.Builder
    }
    public func getBuilder() -> IGPChannelAvatarAdd.Builder {
        return classBuilder() as! IGPChannelAvatarAdd.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPChannelAvatarAdd.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPChannelAvatarAdd.Builder()
    }
    public func toBuilder() throws -> IGPChannelAvatarAdd.Builder {
        return try IGPChannelAvatarAdd.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPChannelAvatarAdd) throws -> IGPChannelAvatarAdd.Builder {
        return try IGPChannelAvatarAdd.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpRequest {
            jsonMap["IGPRequest"] = try igpRequest.encode()
        }
        if hasIgpAttachment {
            jsonMap["IGPAttachment"] = igpAttachment
        }
        if hasIgpRoomId {
            jsonMap["IGPRoomId"] = "\(igpRoomId)"
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpRequest {
            output += "\(indent) igpRequest {\n"
            if let outDescIgpRequest = igpRequest {
                output += try outDescIgpRequest.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpAttachment {
            output += "\(indent) igpAttachment: \(igpAttachment) \n"
        }
        if hasIgpRoomId {
            output += "\(indent) igpRoomId: \(igpRoomId) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpRequest {
                if let hashValueigpRequest = igpRequest?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpRequest
                }
            }
            if hasIgpAttachment {
                hashCode = (hashCode &* 31) &+ igpAttachment.hashValue
            }
            if hasIgpRoomId {
                hashCode = (hashCode &* 31) &+ igpRoomId.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPChannelAvatarAdd"
    }
    override public func className() -> String {
        return "IGPChannelAvatarAdd"
    }
    //Meta information declaration end

    final public class Builder : GeneratedRequestMessageBuilder {
        fileprivate var builderResult:IGPChannelAvatarAdd = IGPChannelAvatarAdd()
        public func getMessage() -> IGPChannelAvatarAdd {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpRequest:IGPRequest! {
            get {
                if igpRequestBuilder_ != nil {
                    builderResult.igpRequest = igpRequestBuilder_.getMessage()
                }
                return builderResult.igpRequest
            }
            set (value) {
                builderResult.hasIgpRequest = true
                builderResult.igpRequest = value
            }
        }
        public var hasIgpRequest:Bool {
            get {
                return builderResult.hasIgpRequest
            }
        }
        fileprivate var igpRequestBuilder_:IGPRequest.Builder! {
            didSet {
                builderResult.hasIgpRequest = true
            }
        }
        public func getIgpRequestBuilder() -> IGPRequest.Builder {
            if igpRequestBuilder_ == nil {
                igpRequestBuilder_ = IGPRequest.Builder()
                builderResult.igpRequest = igpRequestBuilder_.getMessage()
                if igpRequest != nil {
                    try! igpRequestBuilder_.mergeFrom(other: igpRequest)
                }
            }
            return igpRequestBuilder_
        }
        @discardableResult
        public override func setIgpRequest(_ value:IGPRequest!) -> IGPChannelAvatarAdd.Builder {
            self.igpRequest = value
            return self
        }
        @discardableResult
        public func mergeIgpRequest(value:IGPRequest) throws -> IGPChannelAvatarAdd.Builder {
            if builderResult.hasIgpRequest {
                builderResult.igpRequest = try IGPRequest.builderWithPrototype(prototype:builderResult.igpRequest).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpRequest = value
            }
            builderResult.hasIgpRequest = true
            return self
        }
        @discardableResult
        public func clearIgpRequest() -> IGPChannelAvatarAdd.Builder {
            igpRequestBuilder_ = nil
            builderResult.hasIgpRequest = false
            builderResult.igpRequest = nil
            return self
        }
        public var igpAttachment:String {
            get {
                return builderResult.igpAttachment
            }
            set (value) {
                builderResult.hasIgpAttachment = true
                builderResult.igpAttachment = value
            }
        }
        public var hasIgpAttachment:Bool {
            get {
                return builderResult.hasIgpAttachment
            }
        }
        @discardableResult
        public func setIgpAttachment(_ value:String) -> IGPChannelAvatarAdd.Builder {
            self.igpAttachment = value
            return self
        }
        @discardableResult
        public func clearIgpAttachment() -> IGPChannelAvatarAdd.Builder{
            builderResult.hasIgpAttachment = false
            builderResult.igpAttachment = ""
            return self
        }
        public var igpRoomId:Int64 {
            get {
                return builderResult.igpRoomId
            }
            set (value) {
                builderResult.hasIgpRoomId = true
                builderResult.igpRoomId = value
            }
        }
        public var hasIgpRoomId:Bool {
            get {
                return builderResult.hasIgpRoomId
            }
        }
        @discardableResult
        public func setIgpRoomId(_ value:Int64) -> IGPChannelAvatarAdd.Builder {
            self.igpRoomId = value
            return self
        }
        @discardableResult
        public func clearIgpRoomId() -> IGPChannelAvatarAdd.Builder{
            builderResult.hasIgpRoomId = false
            builderResult.igpRoomId = Int64(0)
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPChannelAvatarAdd.Builder {
            builderResult = IGPChannelAvatarAdd()
            return self
        }
        override public func clone() throws -> IGPChannelAvatarAdd.Builder {
            return try IGPChannelAvatarAdd.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPChannelAvatarAdd {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPChannelAvatarAdd {
            let returnMe:IGPChannelAvatarAdd = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPChannelAvatarAdd) throws -> IGPChannelAvatarAdd.Builder {
            if other == IGPChannelAvatarAdd() {
                return self
            }
            if (other.hasIgpRequest) {
                try mergeIgpRequest(value: other.igpRequest)
            }
            if other.hasIgpAttachment {
                igpAttachment = other.igpAttachment
            }
            if other.hasIgpRoomId {
                igpRoomId = other.igpRoomId
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPChannelAvatarAdd.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAdd.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPRequest.Builder = IGPRequest.Builder()
                    if hasIgpRequest {
                        try subBuilder.mergeFrom(other: igpRequest)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpRequest = subBuilder.buildPartial()

                case 18:
                    igpAttachment = try codedInputStream.readString()

                case 24:
                    igpRoomId = try codedInputStream.readInt64()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPChannelAvatarAdd.Builder {
            let resultDecodedBuilder = IGPChannelAvatarAdd.Builder()
            if let jsonValueIgpRequest = jsonMap["IGPRequest"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpRequest = try IGPRequest.Builder.decodeToBuilder(jsonMap:jsonValueIgpRequest).build()

            }
            if let jsonValueIgpAttachment = jsonMap["IGPAttachment"] as? String {
                resultDecodedBuilder.igpAttachment = jsonValueIgpAttachment
            }
            if let jsonValueIgpRoomId = jsonMap["IGPRoomId"] as? String {
                resultDecodedBuilder.igpRoomId = Int64(jsonValueIgpRoomId)!
            } else if let jsonValueIgpRoomId = jsonMap["IGPRoomId"] as? Int {
                resultDecodedBuilder.igpRoomId = Int64(jsonValueIgpRoomId)
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPChannelAvatarAdd.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPChannelAvatarAdd.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

final public class IGPChannelAvatarAddResponse : GeneratedResponseMessage {

    public static func == (lhs: IGPChannelAvatarAddResponse, rhs: IGPChannelAvatarAddResponse) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpResponse == rhs.hasIgpResponse) && (!lhs.hasIgpResponse || lhs.igpResponse == rhs.igpResponse)
        fieldCheck = fieldCheck && (lhs.hasIgpAvatar == rhs.hasIgpAvatar) && (!lhs.hasIgpAvatar || lhs.igpAvatar == rhs.igpAvatar)
        fieldCheck = fieldCheck && (lhs.hasIgpRoomId == rhs.hasIgpRoomId) && (!lhs.hasIgpRoomId || lhs.igpRoomId == rhs.igpRoomId)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpAvatar:IGPAvatar!
    public fileprivate(set) var hasIgpAvatar:Bool = false
    public fileprivate(set) var igpRoomId:Int64 = Int64(0)
    public fileprivate(set) var hasIgpRoomId:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpResponse {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpResponse)
        }
        if hasIgpAvatar {
            try codedOutputStream.writeMessage(fieldNumber: 2, value:igpAvatar)
        }
        if hasIgpRoomId {
            try codedOutputStream.writeInt64(fieldNumber: 3, value:igpRoomId)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpResponse {
            if let varSizeigpResponse = igpResponse?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpResponse
            }
        }
        if hasIgpAvatar {
            if let varSizeigpAvatar = igpAvatar?.computeMessageSize(fieldNumber: 2) {
                serialize_size += varSizeigpAvatar
            }
        }
        if hasIgpRoomId {
            serialize_size += igpRoomId.computeInt64Size(fieldNumber: 3)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPChannelAvatarAddResponse.Builder {
        return IGPChannelAvatarAddResponse.classBuilder() as! IGPChannelAvatarAddResponse.Builder
    }
    public func getBuilder() -> IGPChannelAvatarAddResponse.Builder {
        return classBuilder() as! IGPChannelAvatarAddResponse.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPChannelAvatarAddResponse.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPChannelAvatarAddResponse.Builder()
    }
    public func toBuilder() throws -> IGPChannelAvatarAddResponse.Builder {
        return try IGPChannelAvatarAddResponse.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPChannelAvatarAddResponse) throws -> IGPChannelAvatarAddResponse.Builder {
        return try IGPChannelAvatarAddResponse.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpResponse {
            jsonMap["IGPResponse"] = try igpResponse.encode()
        }
        if hasIgpAvatar {
            jsonMap["IGPAvatar"] = try igpAvatar.encode()
        }
        if hasIgpRoomId {
            jsonMap["IGPRoomId"] = "\(igpRoomId)"
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpResponse {
            output += "\(indent) igpResponse {\n"
            if let outDescIgpResponse = igpResponse {
                output += try outDescIgpResponse.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpAvatar {
            output += "\(indent) igpAvatar {\n"
            if let outDescIgpAvatar = igpAvatar {
                output += try outDescIgpAvatar.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpRoomId {
            output += "\(indent) igpRoomId: \(igpRoomId) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpResponse {
                if let hashValueigpResponse = igpResponse?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpResponse
                }
            }
            if hasIgpAvatar {
                if let hashValueigpAvatar = igpAvatar?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpAvatar
                }
            }
            if hasIgpRoomId {
                hashCode = (hashCode &* 31) &+ igpRoomId.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPChannelAvatarAddResponse"
    }
    override public func className() -> String {
        return "IGPChannelAvatarAddResponse"
    }
    //Meta information declaration end

    final public class Builder : GeneratedResponseMessageBuilder {
        fileprivate var builderResult:IGPChannelAvatarAddResponse = IGPChannelAvatarAddResponse()
        public func getMessage() -> IGPChannelAvatarAddResponse {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpResponse:IGPResponse! {
            get {
                if igpResponseBuilder_ != nil {
                    builderResult.igpResponse = igpResponseBuilder_.getMessage()
                }
                return builderResult.igpResponse
            }
            set (value) {
                builderResult.hasIgpResponse = true
                builderResult.igpResponse = value
            }
        }
        public var hasIgpResponse:Bool {
            get {
                return builderResult.hasIgpResponse
            }
        }
        fileprivate var igpResponseBuilder_:IGPResponse.Builder! {
            didSet {
                builderResult.hasIgpResponse = true
            }
        }
        public func getIgpResponseBuilder() -> IGPResponse.Builder {
            if igpResponseBuilder_ == nil {
                igpResponseBuilder_ = IGPResponse.Builder()
                builderResult.igpResponse = igpResponseBuilder_.getMessage()
                if igpResponse != nil {
                    try! igpResponseBuilder_.mergeFrom(other: igpResponse)
                }
            }
            return igpResponseBuilder_
        }
        @discardableResult
        public func setIgpResponse(_ value:IGPResponse!) -> IGPChannelAvatarAddResponse.Builder {
            self.igpResponse = value
            return self
        }
        @discardableResult
        public func mergeIgpResponse(value:IGPResponse) throws -> IGPChannelAvatarAddResponse.Builder {
            if builderResult.hasIgpResponse {
                builderResult.igpResponse = try IGPResponse.builderWithPrototype(prototype:builderResult.igpResponse).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpResponse = value
            }
            builderResult.hasIgpResponse = true
            return self
        }
        @discardableResult
        public func clearIgpResponse() -> IGPChannelAvatarAddResponse.Builder {
            igpResponseBuilder_ = nil
            builderResult.hasIgpResponse = false
            builderResult.igpResponse = nil
            return self
        }
        public var igpAvatar:IGPAvatar! {
            get {
                if igpAvatarBuilder_ != nil {
                    builderResult.igpAvatar = igpAvatarBuilder_.getMessage()
                }
                return builderResult.igpAvatar
            }
            set (value) {
                builderResult.hasIgpAvatar = true
                builderResult.igpAvatar = value
            }
        }
        public var hasIgpAvatar:Bool {
            get {
                return builderResult.hasIgpAvatar
            }
        }
        fileprivate var igpAvatarBuilder_:IGPAvatar.Builder! {
            didSet {
                builderResult.hasIgpAvatar = true
            }
        }
        public func getIgpAvatarBuilder() -> IGPAvatar.Builder {
            if igpAvatarBuilder_ == nil {
                igpAvatarBuilder_ = IGPAvatar.Builder()
                builderResult.igpAvatar = igpAvatarBuilder_.getMessage()
                if igpAvatar != nil {
                    try! igpAvatarBuilder_.mergeFrom(other: igpAvatar)
                }
            }
            return igpAvatarBuilder_
        }
        @discardableResult
        public func setIgpAvatar(_ value:IGPAvatar!) -> IGPChannelAvatarAddResponse.Builder {
            self.igpAvatar = value
            return self
        }
        @discardableResult
        public func mergeIgpAvatar(value:IGPAvatar) throws -> IGPChannelAvatarAddResponse.Builder {
            if builderResult.hasIgpAvatar {
                builderResult.igpAvatar = try IGPAvatar.builderWithPrototype(prototype:builderResult.igpAvatar).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpAvatar = value
            }
            builderResult.hasIgpAvatar = true
            return self
        }
        @discardableResult
        public func clearIgpAvatar() -> IGPChannelAvatarAddResponse.Builder {
            igpAvatarBuilder_ = nil
            builderResult.hasIgpAvatar = false
            builderResult.igpAvatar = nil
            return self
        }
        public var igpRoomId:Int64 {
            get {
                return builderResult.igpRoomId
            }
            set (value) {
                builderResult.hasIgpRoomId = true
                builderResult.igpRoomId = value
            }
        }
        public var hasIgpRoomId:Bool {
            get {
                return builderResult.hasIgpRoomId
            }
        }
        @discardableResult
        public func setIgpRoomId(_ value:Int64) -> IGPChannelAvatarAddResponse.Builder {
            self.igpRoomId = value
            return self
        }
        @discardableResult
        public func clearIgpRoomId() -> IGPChannelAvatarAddResponse.Builder{
            builderResult.hasIgpRoomId = false
            builderResult.igpRoomId = Int64(0)
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPChannelAvatarAddResponse.Builder {
            builderResult = IGPChannelAvatarAddResponse()
            return self
        }
        override public func clone() throws -> IGPChannelAvatarAddResponse.Builder {
            return try IGPChannelAvatarAddResponse.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPChannelAvatarAddResponse {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPChannelAvatarAddResponse {
            let returnMe:IGPChannelAvatarAddResponse = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPChannelAvatarAddResponse) throws -> IGPChannelAvatarAddResponse.Builder {
            if other == IGPChannelAvatarAddResponse() {
                return self
            }
            if (other.hasIgpResponse) {
                try mergeIgpResponse(value: other.igpResponse)
            }
            if (other.hasIgpAvatar) {
                try mergeIgpAvatar(value: other.igpAvatar)
            }
            if other.hasIgpRoomId {
                igpRoomId = other.igpRoomId
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPChannelAvatarAddResponse.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAddResponse.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPResponse.Builder = IGPResponse.Builder()
                    if hasIgpResponse {
                        try subBuilder.mergeFrom(other: igpResponse)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpResponse = subBuilder.buildPartial()

                case 18:
                    let subBuilder:IGPAvatar.Builder = IGPAvatar.Builder()
                    if hasIgpAvatar {
                        try subBuilder.mergeFrom(other: igpAvatar)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpAvatar = subBuilder.buildPartial()

                case 24:
                    igpRoomId = try codedInputStream.readInt64()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPChannelAvatarAddResponse.Builder {
            let resultDecodedBuilder = IGPChannelAvatarAddResponse.Builder()
            if let jsonValueIgpResponse = jsonMap["IGPResponse"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpResponse = try IGPResponse.Builder.decodeToBuilder(jsonMap:jsonValueIgpResponse).build()

            }
            if let jsonValueIgpAvatar = jsonMap["IGPAvatar"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpAvatar = try IGPAvatar.Builder.decodeToBuilder(jsonMap:jsonValueIgpAvatar).build()

            }
            if let jsonValueIgpRoomId = jsonMap["IGPRoomId"] as? String {
                resultDecodedBuilder.igpRoomId = Int64(jsonValueIgpRoomId)!
            } else if let jsonValueIgpRoomId = jsonMap["IGPRoomId"] as? Int {
                resultDecodedBuilder.igpRoomId = Int64(jsonValueIgpRoomId)
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPChannelAvatarAddResponse.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPChannelAvatarAddResponse.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

extension IGPChannelAvatarAdd: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPChannelAvatarAdd> {
        var mergedArray = Array<IGPChannelAvatarAdd>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPChannelAvatarAdd? {
        return try IGPChannelAvatarAdd.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder().mergeFrom(data: data, extensionRegistry:ChannelAvatarAddRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAdd {
        return try IGPChannelAvatarAdd.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpRequest": return self.igpRequest
        case "igpAttachment": return self.igpAttachment
        case "igpRoomId": return self.igpRoomId
        default: return nil
        }
    }
}
extension IGPChannelAvatarAdd.Builder: GeneratedMessageBuilderProtocol {
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpRequest": return self.igpRequest
            case "igpAttachment": return self.igpAttachment
            case "igpRoomId": return self.igpRoomId
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpRequest":
                guard let newSubscriptValue = newSubscriptValue as? IGPRequest else {
                    return
                }
                self.igpRequest = newSubscriptValue
            case "igpAttachment":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpAttachment = newSubscriptValue
            case "igpRoomId":
                guard let newSubscriptValue = newSubscriptValue as? Int64 else {
                    return
                }
                self.igpRoomId = newSubscriptValue
            default: return
            }
        }
    }
}
extension IGPChannelAvatarAddResponse: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPChannelAvatarAddResponse> {
        var mergedArray = Array<IGPChannelAvatarAddResponse>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPChannelAvatarAddResponse? {
        return try IGPChannelAvatarAddResponse.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder().mergeFrom(data: data, extensionRegistry:ChannelAvatarAddRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPChannelAvatarAddResponse {
        return try IGPChannelAvatarAddResponse.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpResponse": return self.igpResponse
        case "igpAvatar": return self.igpAvatar
        case "igpRoomId": return self.igpRoomId
        default: return nil
        }
    }
}
extension IGPChannelAvatarAddResponse.Builder: GeneratedMessageBuilderProtocol {
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpResponse": return self.igpResponse
            case "igpAvatar": return self.igpAvatar
            case "igpRoomId": return self.igpRoomId
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpResponse":
                guard let newSubscriptValue = newSubscriptValue as? IGPResponse else {
                    return
                }
                self.igpResponse = newSubscriptValue
            case "igpAvatar":
                guard let newSubscriptValue = newSubscriptValue as? IGPAvatar else {
                    return
                }
                self.igpAvatar = newSubscriptValue
            case "igpRoomId":
                guard let newSubscriptValue = newSubscriptValue as? Int64 else {
                    return
                }
                self.igpRoomId = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
