/// Generated by the Protocol Buffers 3.2.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 3.0.13
/// Source file "FileUploadStatus.proto"
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct FileUploadStatusRoot {
    public static let `default` = FileUploadStatusRoot()
    public var extensionRegistry:ExtensionRegistry

    init() {
        extensionRegistry = ExtensionRegistry()
        registerAllExtensions(registry: extensionRegistry)
        RequestRoot.default.registerAllExtensions(registry: extensionRegistry)
        ResponseRoot.default.registerAllExtensions(registry: extensionRegistry)
    }
    public func registerAllExtensions(registry: ExtensionRegistry) {
    }
}

final public class IGPFileUploadStatus : GeneratedMessage {

    public static func == (lhs: IGPFileUploadStatus, rhs: IGPFileUploadStatus) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpRequest == rhs.hasIgpRequest) && (!lhs.hasIgpRequest || lhs.igpRequest == rhs.igpRequest)
        fieldCheck = fieldCheck && (lhs.hasIgpToken == rhs.hasIgpToken) && (!lhs.hasIgpToken || lhs.igpToken == rhs.igpToken)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpRequest:IGPRequest!
    public fileprivate(set) var hasIgpRequest:Bool = false
    public fileprivate(set) var igpToken:String = ""
    public fileprivate(set) var hasIgpToken:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpRequest {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpRequest)
        }
        if hasIgpToken {
            try codedOutputStream.writeString(fieldNumber: 2, value:igpToken)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpRequest {
            if let varSizeigpRequest = igpRequest?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpRequest
            }
        }
        if hasIgpToken {
            serialize_size += igpToken.computeStringSize(fieldNumber: 2)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPFileUploadStatus.Builder {
        return IGPFileUploadStatus.classBuilder() as! IGPFileUploadStatus.Builder
    }
    public func getBuilder() -> IGPFileUploadStatus.Builder {
        return classBuilder() as! IGPFileUploadStatus.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPFileUploadStatus.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPFileUploadStatus.Builder()
    }
    public func toBuilder() throws -> IGPFileUploadStatus.Builder {
        return try IGPFileUploadStatus.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPFileUploadStatus) throws -> IGPFileUploadStatus.Builder {
        return try IGPFileUploadStatus.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpRequest {
            jsonMap["IGPRequest"] = try igpRequest.encode()
        }
        if hasIgpToken {
            jsonMap["IGPToken"] = igpToken
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpRequest {
            output += "\(indent) igpRequest {\n"
            if let outDescIgpRequest = igpRequest {
                output += try outDescIgpRequest.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpToken {
            output += "\(indent) igpToken: \(igpToken) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpRequest {
                if let hashValueigpRequest = igpRequest?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpRequest
                }
            }
            if hasIgpToken {
                hashCode = (hashCode &* 31) &+ igpToken.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPFileUploadStatus"
    }
    override public func className() -> String {
        return "IGPFileUploadStatus"
    }
    //Meta information declaration end

    final public class Builder : GeneratedRequestMessageBuilder {
        fileprivate var builderResult:IGPFileUploadStatus = IGPFileUploadStatus()
        public func getMessage() -> IGPFileUploadStatus {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpRequest:IGPRequest! {
            get {
                if igpRequestBuilder_ != nil {
                    builderResult.igpRequest = igpRequestBuilder_.getMessage()
                }
                return builderResult.igpRequest
            }
            set (value) {
                builderResult.hasIgpRequest = true
                builderResult.igpRequest = value
            }
        }
        public var hasIgpRequest:Bool {
            get {
                return builderResult.hasIgpRequest
            }
        }
        fileprivate var igpRequestBuilder_:IGPRequest.Builder! {
            didSet {
                builderResult.hasIgpRequest = true
            }
        }
        public func getIgpRequestBuilder() -> IGPRequest.Builder {
            if igpRequestBuilder_ == nil {
                igpRequestBuilder_ = IGPRequest.Builder()
                builderResult.igpRequest = igpRequestBuilder_.getMessage()
                if igpRequest != nil {
                    try! igpRequestBuilder_.mergeFrom(other: igpRequest)
                }
            }
            return igpRequestBuilder_
        }
        @discardableResult
        public override func setIgpRequest(_ value:IGPRequest!) -> IGPFileUploadStatus.Builder {
            self.igpRequest = value
            return self
        }
        @discardableResult
        public func mergeIgpRequest(value:IGPRequest) throws -> IGPFileUploadStatus.Builder {
            if builderResult.hasIgpRequest {
                builderResult.igpRequest = try IGPRequest.builderWithPrototype(prototype:builderResult.igpRequest).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpRequest = value
            }
            builderResult.hasIgpRequest = true
            return self
        }
        @discardableResult
        public func clearIgpRequest() -> IGPFileUploadStatus.Builder {
            igpRequestBuilder_ = nil
            builderResult.hasIgpRequest = false
            builderResult.igpRequest = nil
            return self
        }
        public var igpToken:String {
            get {
                return builderResult.igpToken
            }
            set (value) {
                builderResult.hasIgpToken = true
                builderResult.igpToken = value
            }
        }
        public var hasIgpToken:Bool {
            get {
                return builderResult.hasIgpToken
            }
        }
        @discardableResult
        public func setIgpToken(_ value:String) -> IGPFileUploadStatus.Builder {
            self.igpToken = value
            return self
        }
        @discardableResult
        public func clearIgpToken() -> IGPFileUploadStatus.Builder{
            builderResult.hasIgpToken = false
            builderResult.igpToken = ""
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPFileUploadStatus.Builder {
            builderResult = IGPFileUploadStatus()
            return self
        }
        override public func clone() throws -> IGPFileUploadStatus.Builder {
            return try IGPFileUploadStatus.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPFileUploadStatus {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPFileUploadStatus {
            let returnMe:IGPFileUploadStatus = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPFileUploadStatus) throws -> IGPFileUploadStatus.Builder {
            if other == IGPFileUploadStatus() {
                return self
            }
            if (other.hasIgpRequest) {
                try mergeIgpRequest(value: other.igpRequest)
            }
            if other.hasIgpToken {
                igpToken = other.igpToken
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPFileUploadStatus.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatus.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPRequest.Builder = IGPRequest.Builder()
                    if hasIgpRequest {
                        try subBuilder.mergeFrom(other: igpRequest)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpRequest = subBuilder.buildPartial()

                case 18:
                    igpToken = try codedInputStream.readString()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPFileUploadStatus.Builder {
            let resultDecodedBuilder = IGPFileUploadStatus.Builder()
            if let jsonValueIgpRequest = jsonMap["IGPRequest"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpRequest = try IGPRequest.Builder.decodeToBuilder(jsonMap:jsonValueIgpRequest).build()

            }
            if let jsonValueIgpToken = jsonMap["IGPToken"] as? String {
                resultDecodedBuilder.igpToken = jsonValueIgpToken
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPFileUploadStatus.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPFileUploadStatus.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

final public class IGPFileUploadStatusResponse : GeneratedResponseMessage {

    public static func == (lhs: IGPFileUploadStatusResponse, rhs: IGPFileUploadStatusResponse) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpResponse == rhs.hasIgpResponse) && (!lhs.hasIgpResponse || lhs.igpResponse == rhs.igpResponse)
        fieldCheck = fieldCheck && (lhs.hasIgpStatus == rhs.hasIgpStatus) && (!lhs.hasIgpStatus || lhs.igpStatus == rhs.igpStatus)
        fieldCheck = fieldCheck && (lhs.hasIgpProgress == rhs.hasIgpProgress) && (!lhs.hasIgpProgress || lhs.igpProgress == rhs.igpProgress)
        fieldCheck = fieldCheck && (lhs.hasIgpRecheckDelayMs == rhs.hasIgpRecheckDelayMs) && (!lhs.hasIgpRecheckDelayMs || lhs.igpRecheckDelayMs == rhs.igpRecheckDelayMs)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end



        //Enum type declaration start 

        public enum IGPStatus:Int32, CustomDebugStringConvertible, CustomStringConvertible, Hashable {
            case uploading = 0
            case processing = 1
            case processed = 2
            case corrupted = 3
            public func toString() -> String {
                switch self {
                case .uploading: return "UPLOADING"
                case .processing: return "PROCESSING"
                case .processed: return "PROCESSED"
                case .corrupted: return "CORRUPTED"
                }
            }
            public static func fromString(str:String) throws -> IGPFileUploadStatusResponse.IGPStatus {
                switch str {
                case "UPLOADING":    return .uploading
                case "PROCESSING":    return .processing
                case "PROCESSED":    return .processed
                case "CORRUPTED":    return .corrupted
                default: throw ProtocolBuffersError.invalidProtocolBuffer("Conversion String to Enum has failed.")
                }
            }
            public var debugDescription:String { return getDescription() }
            public var description:String { return getDescription() }
            private func getDescription() -> String { 
                switch self {
                case .uploading: return ".uploading"
                case .processing: return ".processing"
                case .processed: return ".processed"
                case .corrupted: return ".corrupted"
                }
            }
            public var hashValue:Int {
                return self.rawValue.hashValue
            }
            public static func ==(lhs:IGPStatus, rhs:IGPStatus) -> Bool {
                return lhs.hashValue == rhs.hashValue
            }
        }

        //Enum type declaration end 

    public fileprivate(set) var igpStatus:IGPFileUploadStatusResponse.IGPStatus = IGPFileUploadStatusResponse.IGPStatus.uploading
    public fileprivate(set) var hasIgpStatus:Bool = false
    public fileprivate(set) var igpProgress:Double = Double(0)
    public fileprivate(set) var hasIgpProgress:Bool = false

    public fileprivate(set) var igpRecheckDelayMs:Int32 = Int32(0)
    public fileprivate(set) var hasIgpRecheckDelayMs:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpResponse {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpResponse)
        }
        if hasIgpStatus {
            try codedOutputStream.writeEnum(fieldNumber: 2, value:igpStatus.rawValue)
        }
        if hasIgpProgress {
            try codedOutputStream.writeDouble(fieldNumber: 3, value:igpProgress)
        }
        if hasIgpRecheckDelayMs {
            try codedOutputStream.writeInt32(fieldNumber: 4, value:igpRecheckDelayMs)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpResponse {
            if let varSizeigpResponse = igpResponse?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpResponse
            }
        }
        if (hasIgpStatus) {
            serialize_size += igpStatus.rawValue.computeEnumSize(fieldNumber: 2)
        }
        if hasIgpProgress {
            serialize_size += igpProgress.computeDoubleSize(fieldNumber: 3)
        }
        if hasIgpRecheckDelayMs {
            serialize_size += igpRecheckDelayMs.computeInt32Size(fieldNumber: 4)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPFileUploadStatusResponse.Builder {
        return IGPFileUploadStatusResponse.classBuilder() as! IGPFileUploadStatusResponse.Builder
    }
    public func getBuilder() -> IGPFileUploadStatusResponse.Builder {
        return classBuilder() as! IGPFileUploadStatusResponse.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPFileUploadStatusResponse.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPFileUploadStatusResponse.Builder()
    }
    public func toBuilder() throws -> IGPFileUploadStatusResponse.Builder {
        return try IGPFileUploadStatusResponse.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPFileUploadStatusResponse) throws -> IGPFileUploadStatusResponse.Builder {
        return try IGPFileUploadStatusResponse.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpResponse {
            jsonMap["IGPResponse"] = try igpResponse.encode()
        }
        if hasIgpStatus {
            jsonMap["IGPStatus"] = igpStatus.toString()
        }
        if hasIgpProgress {
            jsonMap["IGPProgress"] = Double(igpProgress)
        }
        if hasIgpRecheckDelayMs {
            jsonMap["IGPRecheckDelayMs"] = Int(igpRecheckDelayMs)
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpResponse {
            output += "\(indent) igpResponse {\n"
            if let outDescIgpResponse = igpResponse {
                output += try outDescIgpResponse.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if (hasIgpStatus) {
            output += "\(indent) igpStatus: \(igpStatus.description)\n"
        }
        if hasIgpProgress {
            output += "\(indent) igpProgress: \(igpProgress) \n"
        }
        if hasIgpRecheckDelayMs {
            output += "\(indent) igpRecheckDelayMs: \(igpRecheckDelayMs) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpResponse {
                if let hashValueigpResponse = igpResponse?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpResponse
                }
            }
            if hasIgpStatus {
                 hashCode = (hashCode &* 31) &+ igpStatus.hashValue
            }
            if hasIgpProgress {
                hashCode = (hashCode &* 31) &+ igpProgress.hashValue
            }
            if hasIgpRecheckDelayMs {
                hashCode = (hashCode &* 31) &+ igpRecheckDelayMs.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPFileUploadStatusResponse"
    }
    override public func className() -> String {
        return "IGPFileUploadStatusResponse"
    }
    //Meta information declaration end

    final public class Builder : GeneratedResponseMessageBuilder {
        fileprivate var builderResult:IGPFileUploadStatusResponse = IGPFileUploadStatusResponse()
        public func getMessage() -> IGPFileUploadStatusResponse {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpResponse:IGPResponse! {
            get {
                if igpResponseBuilder_ != nil {
                    builderResult.igpResponse = igpResponseBuilder_.getMessage()
                }
                return builderResult.igpResponse
            }
            set (value) {
                builderResult.hasIgpResponse = true
                builderResult.igpResponse = value
            }
        }
        public var hasIgpResponse:Bool {
            get {
                return builderResult.hasIgpResponse
            }
        }
        fileprivate var igpResponseBuilder_:IGPResponse.Builder! {
            didSet {
                builderResult.hasIgpResponse = true
            }
        }
        public func getIgpResponseBuilder() -> IGPResponse.Builder {
            if igpResponseBuilder_ == nil {
                igpResponseBuilder_ = IGPResponse.Builder()
                builderResult.igpResponse = igpResponseBuilder_.getMessage()
                if igpResponse != nil {
                    try! igpResponseBuilder_.mergeFrom(other: igpResponse)
                }
            }
            return igpResponseBuilder_
        }
        @discardableResult
        public func setIgpResponse(_ value:IGPResponse!) -> IGPFileUploadStatusResponse.Builder {
            self.igpResponse = value
            return self
        }
        @discardableResult
        public func mergeIgpResponse(value:IGPResponse) throws -> IGPFileUploadStatusResponse.Builder {
            if builderResult.hasIgpResponse {
                builderResult.igpResponse = try IGPResponse.builderWithPrototype(prototype:builderResult.igpResponse).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpResponse = value
            }
            builderResult.hasIgpResponse = true
            return self
        }
        @discardableResult
        public func clearIgpResponse() -> IGPFileUploadStatusResponse.Builder {
            igpResponseBuilder_ = nil
            builderResult.hasIgpResponse = false
            builderResult.igpResponse = nil
            return self
        }
            public var igpStatus:IGPFileUploadStatusResponse.IGPStatus {
                get {
                    return builderResult.igpStatus
                }
                set (value) {
                    builderResult.hasIgpStatus = true
                    builderResult.igpStatus = value
                }
            }
            public var hasIgpStatus:Bool{
                get {
                    return builderResult.hasIgpStatus
                }
            }
        @discardableResult
            public func setIgpStatus(_ value:IGPFileUploadStatusResponse.IGPStatus) -> IGPFileUploadStatusResponse.Builder {
              self.igpStatus = value
              return self
            }
        @discardableResult
            public func clearIgpStatus() -> IGPFileUploadStatusResponse.Builder {
               builderResult.hasIgpStatus = false
               builderResult.igpStatus = .uploading
               return self
            }
        public var igpProgress:Double {
            get {
                return builderResult.igpProgress
            }
            set (value) {
                builderResult.hasIgpProgress = true
                builderResult.igpProgress = value
            }
        }
        public var hasIgpProgress:Bool {
            get {
                return builderResult.hasIgpProgress
            }
        }
        @discardableResult
        public func setIgpProgress(_ value:Double) -> IGPFileUploadStatusResponse.Builder {
            self.igpProgress = value
            return self
        }
        @discardableResult
        public func clearIgpProgress() -> IGPFileUploadStatusResponse.Builder{
            builderResult.hasIgpProgress = false
            builderResult.igpProgress = Double(0)
            return self
        }
        public var igpRecheckDelayMs:Int32 {
            get {
                return builderResult.igpRecheckDelayMs
            }
            set (value) {
                builderResult.hasIgpRecheckDelayMs = true
                builderResult.igpRecheckDelayMs = value
            }
        }
        public var hasIgpRecheckDelayMs:Bool {
            get {
                return builderResult.hasIgpRecheckDelayMs
            }
        }
        @discardableResult
        public func setIgpRecheckDelayMs(_ value:Int32) -> IGPFileUploadStatusResponse.Builder {
            self.igpRecheckDelayMs = value
            return self
        }
        @discardableResult
        public func clearIgpRecheckDelayMs() -> IGPFileUploadStatusResponse.Builder{
            builderResult.hasIgpRecheckDelayMs = false
            builderResult.igpRecheckDelayMs = Int32(0)
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPFileUploadStatusResponse.Builder {
            builderResult = IGPFileUploadStatusResponse()
            return self
        }
        override public func clone() throws -> IGPFileUploadStatusResponse.Builder {
            return try IGPFileUploadStatusResponse.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPFileUploadStatusResponse {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPFileUploadStatusResponse {
            let returnMe:IGPFileUploadStatusResponse = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPFileUploadStatusResponse) throws -> IGPFileUploadStatusResponse.Builder {
            if other == IGPFileUploadStatusResponse() {
                return self
            }
            if (other.hasIgpResponse) {
                try mergeIgpResponse(value: other.igpResponse)
            }
            if other.hasIgpStatus {
                igpStatus = other.igpStatus
            }
            if other.hasIgpProgress {
                igpProgress = other.igpProgress
            }
            if other.hasIgpRecheckDelayMs {
                igpRecheckDelayMs = other.igpRecheckDelayMs
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPFileUploadStatusResponse.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatusResponse.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPResponse.Builder = IGPResponse.Builder()
                    if hasIgpResponse {
                        try subBuilder.mergeFrom(other: igpResponse)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpResponse = subBuilder.buildPartial()

                case 16:
                    let valueIntigpStatus = try codedInputStream.readEnum()
                    if let enumsigpStatus = IGPFileUploadStatusResponse.IGPStatus(rawValue:valueIntigpStatus){
                        igpStatus = enumsigpStatus
                    } else {
                        try unknownFieldsBuilder.mergeVarintField(fieldNumber: 2, value:Int64(valueIntigpStatus))
                    }

                case 25:
                    igpProgress = try codedInputStream.readDouble()

                case 32:
                    igpRecheckDelayMs = try codedInputStream.readInt32()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPFileUploadStatusResponse.Builder {
            let resultDecodedBuilder = IGPFileUploadStatusResponse.Builder()
            if let jsonValueIgpResponse = jsonMap["IGPResponse"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpResponse = try IGPResponse.Builder.decodeToBuilder(jsonMap:jsonValueIgpResponse).build()

            }
            if let jsonValueIgpStatus = jsonMap["IGPStatus"] as? String {
                resultDecodedBuilder.igpStatus = try IGPFileUploadStatusResponse.IGPStatus.fromString(str: jsonValueIgpStatus)
            }
            if let jsonValueIgpProgress = jsonMap["IGPProgress"] as? Double {
                resultDecodedBuilder.igpProgress = Double(jsonValueIgpProgress)
            } else if let jsonValueIgpProgress = jsonMap["IGPProgress"] as? String {
                resultDecodedBuilder.igpProgress = Double(jsonValueIgpProgress)!
            }
            if let jsonValueIgpRecheckDelayMs = jsonMap["IGPRecheckDelayMs"] as? Int {
                resultDecodedBuilder.igpRecheckDelayMs = Int32(jsonValueIgpRecheckDelayMs)
            } else if let jsonValueIgpRecheckDelayMs = jsonMap["IGPRecheckDelayMs"] as? String {
                resultDecodedBuilder.igpRecheckDelayMs = Int32(jsonValueIgpRecheckDelayMs)!
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPFileUploadStatusResponse.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPFileUploadStatusResponse.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

extension IGPFileUploadStatus: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPFileUploadStatus> {
        var mergedArray = Array<IGPFileUploadStatus>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPFileUploadStatus? {
        return try IGPFileUploadStatus.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder().mergeFrom(data: data, extensionRegistry:FileUploadStatusRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatus {
        return try IGPFileUploadStatus.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpRequest": return self.igpRequest
        case "igpToken": return self.igpToken
        default: return nil
        }
    }
}
extension IGPFileUploadStatus.Builder: GeneratedMessageBuilderProtocol {
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpRequest": return self.igpRequest
            case "igpToken": return self.igpToken
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpRequest":
                guard let newSubscriptValue = newSubscriptValue as? IGPRequest else {
                    return
                }
                self.igpRequest = newSubscriptValue
            case "igpToken":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpToken = newSubscriptValue
            default: return
            }
        }
    }
}
extension IGPFileUploadStatusResponse: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPFileUploadStatusResponse> {
        var mergedArray = Array<IGPFileUploadStatusResponse>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPFileUploadStatusResponse? {
        return try IGPFileUploadStatusResponse.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder().mergeFrom(data: data, extensionRegistry:FileUploadStatusRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPFileUploadStatusResponse {
        return try IGPFileUploadStatusResponse.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpResponse": return self.igpResponse
        case "igpStatus": return self.igpStatus
        case "igpProgress": return self.igpProgress
        case "igpRecheckDelayMs": return self.igpRecheckDelayMs
        default: return nil
        }
    }
}
extension IGPFileUploadStatusResponse.Builder: GeneratedMessageBuilderProtocol {
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpResponse": return self.igpResponse
            case "igpStatus": return self.igpStatus
            case "igpProgress": return self.igpProgress
            case "igpRecheckDelayMs": return self.igpRecheckDelayMs
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpResponse":
                guard let newSubscriptValue = newSubscriptValue as? IGPResponse else {
                    return
                }
                self.igpResponse = newSubscriptValue
            case "igpStatus":
                guard let newSubscriptValue = newSubscriptValue as? IGPFileUploadStatusResponse.IGPStatus else {
                    return
                }
                self.igpStatus = newSubscriptValue
            case "igpProgress":
                guard let newSubscriptValue = newSubscriptValue as? Double else {
                    return
                }
                self.igpProgress = newSubscriptValue
            case "igpRecheckDelayMs":
                guard let newSubscriptValue = newSubscriptValue as? Int32 else {
                    return
                }
                self.igpRecheckDelayMs = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
