/// Generated by the Protocol Buffers 3.4.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 3.0.22
/// Source file "GeoUpdateComment.proto"
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct GeoUpdateCommentRoot {
    public static let `default` = GeoUpdateCommentRoot()
    public var extensionRegistry:ExtensionRegistry

    init() {
        extensionRegistry = ExtensionRegistry()
        registerAllExtensions(registry: extensionRegistry)
        RequestRoot.default.registerAllExtensions(registry: extensionRegistry)
        ResponseRoot.default.registerAllExtensions(registry: extensionRegistry)
    }
    public func registerAllExtensions(registry: ExtensionRegistry) {
    }
}

final public class IGPGeoUpdateComment : GeneratedMessage {
    public typealias BuilderType = IGPGeoUpdateComment.Builder

    public static func == (lhs: IGPGeoUpdateComment, rhs: IGPGeoUpdateComment) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpRequest == rhs.hasIgpRequest) && (!lhs.hasIgpRequest || lhs.igpRequest == rhs.igpRequest)
        fieldCheck = fieldCheck && (lhs.hasIgpComment == rhs.hasIgpComment) && (!lhs.hasIgpComment || lhs.igpComment == rhs.igpComment)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpRequest:IGPRequest!
    public fileprivate(set) var hasIgpRequest:Bool = false
    public fileprivate(set) var igpComment:String! = nil
    public fileprivate(set) var hasIgpComment:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpRequest {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpRequest)
        }
        if hasIgpComment {
            try codedOutputStream.writeString(fieldNumber: 2, value:igpComment)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpRequest {
            if let varSizeigpRequest = igpRequest?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpRequest
            }
        }
        if hasIgpComment {
            serialize_size += igpComment.computeStringSize(fieldNumber: 2)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPGeoUpdateComment.Builder {
        return IGPGeoUpdateComment.classBuilder() as! IGPGeoUpdateComment.Builder
    }
    public func getBuilder() -> IGPGeoUpdateComment.Builder {
        return classBuilder() as! IGPGeoUpdateComment.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdateComment.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdateComment.Builder()
    }
    public func toBuilder() throws -> IGPGeoUpdateComment.Builder {
        return try IGPGeoUpdateComment.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPGeoUpdateComment) throws -> IGPGeoUpdateComment.Builder {
        return try IGPGeoUpdateComment.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpRequest {
            jsonMap["IGPRequest"] = try igpRequest.encode()
        }
        if hasIgpComment {
            jsonMap["IGPComment"] = igpComment
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpRequest {
            output += "\(indent) igpRequest {\n"
            if let outDescIgpRequest = igpRequest {
                output += try outDescIgpRequest.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpComment {
            output += "\(indent) igpComment: \(igpComment) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpRequest {
                if let hashValueigpRequest = igpRequest?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpRequest
                }
            }
            if hasIgpComment {
                hashCode = (hashCode &* 31) &+ igpComment.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPGeoUpdateComment"
    }
    override public func className() -> String {
        return "IGPGeoUpdateComment"
    }
    //Meta information declaration end

    final public class Builder : GeneratedRequestMessageBuilder {
        fileprivate var builderResult:IGPGeoUpdateComment = IGPGeoUpdateComment()
        public func getMessage() -> IGPGeoUpdateComment {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpRequest:IGPRequest! {
            get {
                if igpRequestBuilder_ != nil {
                    builderResult.igpRequest = igpRequestBuilder_.getMessage()
                }
                return builderResult.igpRequest
            }
            set (value) {
                builderResult.hasIgpRequest = true
                builderResult.igpRequest = value
            }
        }
        public var hasIgpRequest:Bool {
            get {
                return builderResult.hasIgpRequest
            }
        }
        fileprivate var igpRequestBuilder_:IGPRequest.Builder! {
            didSet {
                builderResult.hasIgpRequest = true
            }
        }
        public func getIgpRequestBuilder() -> IGPRequest.Builder {
            if igpRequestBuilder_ == nil {
                igpRequestBuilder_ = IGPRequest.Builder()
                builderResult.igpRequest = igpRequestBuilder_.getMessage()
                if igpRequest != nil {
                    try! igpRequestBuilder_.mergeFrom(other: igpRequest)
                }
            }
            return igpRequestBuilder_
        }
        @discardableResult
        public override func setIgpRequest(_ value:IGPRequest!) -> IGPGeoUpdateComment.Builder {
            self.igpRequest = value
            return self
        }
        @discardableResult
        public func mergeIgpRequest(value:IGPRequest) throws -> IGPGeoUpdateComment.Builder {
            if builderResult.hasIgpRequest {
                builderResult.igpRequest = try IGPRequest.builderWithPrototype(prototype:builderResult.igpRequest).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpRequest = value
            }
            builderResult.hasIgpRequest = true
            return self
        }
        @discardableResult
        public func clearIgpRequest() -> IGPGeoUpdateComment.Builder {
            igpRequestBuilder_ = nil
            builderResult.hasIgpRequest = false
            builderResult.igpRequest = nil
            return self
        }
        public var igpComment:String {
            get {
                return builderResult.igpComment
            }
            set (value) {
                builderResult.hasIgpComment = true
                builderResult.igpComment = value
            }
        }
        public var hasIgpComment:Bool {
            get {
                return builderResult.hasIgpComment
            }
        }
        @discardableResult
        public func setIgpComment(_ value:String) -> IGPGeoUpdateComment.Builder {
            self.igpComment = value
            return self
        }
        @discardableResult
        public func clearIgpComment() -> IGPGeoUpdateComment.Builder{
            builderResult.hasIgpComment = false
            builderResult.igpComment = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPGeoUpdateComment.Builder {
            builderResult = IGPGeoUpdateComment()
            return self
        }
        override public func clone() throws -> IGPGeoUpdateComment.Builder {
            return try IGPGeoUpdateComment.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPGeoUpdateComment {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPGeoUpdateComment {
            let returnMe:IGPGeoUpdateComment = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPGeoUpdateComment) throws -> IGPGeoUpdateComment.Builder {
            if other == IGPGeoUpdateComment() {
                return self
            }
            if (other.hasIgpRequest) {
                try mergeIgpRequest(value: other.igpRequest)
            }
            if other.hasIgpComment {
                igpComment = other.igpComment
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdateComment.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateComment.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPRequest.Builder = IGPRequest.Builder()
                    if hasIgpRequest {
                        try subBuilder.mergeFrom(other: igpRequest)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpRequest = subBuilder.buildPartial()

                case 18:
                    igpComment = try codedInputStream.readString()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdateComment.Builder {
            let resultDecodedBuilder = IGPGeoUpdateComment.Builder()
            if let jsonValueIgpRequest = jsonMap["IGPRequest"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpRequest = try IGPRequest.Builder.decodeToBuilder(jsonMap:jsonValueIgpRequest).build()

            }
            if let jsonValueIgpComment = jsonMap["IGPComment"] as? String {
                resultDecodedBuilder.igpComment = jsonValueIgpComment
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPGeoUpdateComment.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPGeoUpdateComment.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

final public class IGPGeoUpdateCommentResponse : GeneratedResponseMessage {
    public typealias BuilderType = IGPGeoUpdateCommentResponse.Builder

    public static func == (lhs: IGPGeoUpdateCommentResponse, rhs: IGPGeoUpdateCommentResponse) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpResponse == rhs.hasIgpResponse) && (!lhs.hasIgpResponse || lhs.igpResponse == rhs.igpResponse)
        fieldCheck = fieldCheck && (lhs.hasIgpComment == rhs.hasIgpComment) && (!lhs.hasIgpComment || lhs.igpComment == rhs.igpComment)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpComment:String! = nil
    public fileprivate(set) var hasIgpComment:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpResponse {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpResponse)
        }
        if hasIgpComment {
            try codedOutputStream.writeString(fieldNumber: 2, value:igpComment)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpResponse {
            if let varSizeigpResponse = igpResponse?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpResponse
            }
        }
        if hasIgpComment {
            serialize_size += igpComment.computeStringSize(fieldNumber: 2)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPGeoUpdateCommentResponse.Builder {
        return IGPGeoUpdateCommentResponse.classBuilder() as! IGPGeoUpdateCommentResponse.Builder
    }
    public func getBuilder() -> IGPGeoUpdateCommentResponse.Builder {
        return classBuilder() as! IGPGeoUpdateCommentResponse.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdateCommentResponse.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdateCommentResponse.Builder()
    }
    public func toBuilder() throws -> IGPGeoUpdateCommentResponse.Builder {
        return try IGPGeoUpdateCommentResponse.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPGeoUpdateCommentResponse) throws -> IGPGeoUpdateCommentResponse.Builder {
        return try IGPGeoUpdateCommentResponse.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpResponse {
            jsonMap["IGPResponse"] = try igpResponse.encode()
        }
        if hasIgpComment {
            jsonMap["IGPComment"] = igpComment
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpResponse {
            output += "\(indent) igpResponse {\n"
            if let outDescIgpResponse = igpResponse {
                output += try outDescIgpResponse.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpComment {
            output += "\(indent) igpComment: \(igpComment) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpResponse {
                if let hashValueigpResponse = igpResponse?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpResponse
                }
            }
            if hasIgpComment {
                hashCode = (hashCode &* 31) &+ igpComment.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPGeoUpdateCommentResponse"
    }
    override public func className() -> String {
        return "IGPGeoUpdateCommentResponse"
    }
    //Meta information declaration end

    final public class Builder : GeneratedResponseMessageBuilder {
        fileprivate var builderResult:IGPGeoUpdateCommentResponse = IGPGeoUpdateCommentResponse()
        public func getMessage() -> IGPGeoUpdateCommentResponse {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpResponse:IGPResponse! {
            get {
                if igpResponseBuilder_ != nil {
                    builderResult.igpResponse = igpResponseBuilder_.getMessage()
                }
                return builderResult.igpResponse
            }
            set (value) {
                builderResult.hasIgpResponse = true
                builderResult.igpResponse = value
            }
        }
        public var hasIgpResponse:Bool {
            get {
                return builderResult.hasIgpResponse
            }
        }
        fileprivate var igpResponseBuilder_:IGPResponse.Builder! {
            didSet {
                builderResult.hasIgpResponse = true
            }
        }
        public func getIgpResponseBuilder() -> IGPResponse.Builder {
            if igpResponseBuilder_ == nil {
                igpResponseBuilder_ = IGPResponse.Builder()
                builderResult.igpResponse = igpResponseBuilder_.getMessage()
                if igpResponse != nil {
                    try! igpResponseBuilder_.mergeFrom(other: igpResponse)
                }
            }
            return igpResponseBuilder_
        }
        @discardableResult
        public func setIgpResponse(_ value:IGPResponse!) -> IGPGeoUpdateCommentResponse.Builder {
            self.igpResponse = value
            return self
        }
        @discardableResult
        public func mergeIgpResponse(value:IGPResponse) throws -> IGPGeoUpdateCommentResponse.Builder {
            if builderResult.hasIgpResponse {
                builderResult.igpResponse = try IGPResponse.builderWithPrototype(prototype:builderResult.igpResponse).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpResponse = value
            }
            builderResult.hasIgpResponse = true
            return self
        }
        @discardableResult
        public func clearIgpResponse() -> IGPGeoUpdateCommentResponse.Builder {
            igpResponseBuilder_ = nil
            builderResult.hasIgpResponse = false
            builderResult.igpResponse = nil
            return self
        }
        public var igpComment:String {
            get {
                return builderResult.igpComment
            }
            set (value) {
                builderResult.hasIgpComment = true
                builderResult.igpComment = value
            }
        }
        public var hasIgpComment:Bool {
            get {
                return builderResult.hasIgpComment
            }
        }
        @discardableResult
        public func setIgpComment(_ value:String) -> IGPGeoUpdateCommentResponse.Builder {
            self.igpComment = value
            return self
        }
        @discardableResult
        public func clearIgpComment() -> IGPGeoUpdateCommentResponse.Builder{
            builderResult.hasIgpComment = false
            builderResult.igpComment = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPGeoUpdateCommentResponse.Builder {
            builderResult = IGPGeoUpdateCommentResponse()
            return self
        }
        override public func clone() throws -> IGPGeoUpdateCommentResponse.Builder {
            return try IGPGeoUpdateCommentResponse.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPGeoUpdateCommentResponse {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPGeoUpdateCommentResponse {
            let returnMe:IGPGeoUpdateCommentResponse = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPGeoUpdateCommentResponse) throws -> IGPGeoUpdateCommentResponse.Builder {
            if other == IGPGeoUpdateCommentResponse() {
                return self
            }
            if (other.hasIgpResponse) {
                try mergeIgpResponse(value: other.igpResponse)
            }
            if other.hasIgpComment {
                igpComment = other.igpComment
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdateCommentResponse.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateCommentResponse.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPResponse.Builder = IGPResponse.Builder()
                    if hasIgpResponse {
                        try subBuilder.mergeFrom(other: igpResponse)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpResponse = subBuilder.buildPartial()

                case 18:
                    igpComment = try codedInputStream.readString()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdateCommentResponse.Builder {
            let resultDecodedBuilder = IGPGeoUpdateCommentResponse.Builder()
            if let jsonValueIgpResponse = jsonMap["IGPResponse"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpResponse = try IGPResponse.Builder.decodeToBuilder(jsonMap:jsonValueIgpResponse).build()

            }
            if let jsonValueIgpComment = jsonMap["IGPComment"] as? String {
                resultDecodedBuilder.igpComment = jsonValueIgpComment
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPGeoUpdateCommentResponse.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPGeoUpdateCommentResponse.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

extension IGPGeoUpdateComment: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPGeoUpdateComment> {
        var mergedArray = Array<IGPGeoUpdateComment>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPGeoUpdateComment? {
        return try IGPGeoUpdateComment.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder().mergeFrom(data: data, extensionRegistry:GeoUpdateCommentRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateComment {
        return try IGPGeoUpdateComment.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpRequest": return self.igpRequest
        case "igpComment": return self.igpComment
        default: return nil
        }
    }
}
extension IGPGeoUpdateComment.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = IGPGeoUpdateComment
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpRequest": return self.igpRequest
            case "igpComment": return self.igpComment
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpRequest":
                guard let newSubscriptValue = newSubscriptValue as? IGPRequest else {
                    return
                }
                self.igpRequest = newSubscriptValue
            case "igpComment":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpComment = newSubscriptValue
            default: return
            }
        }
    }
}
extension IGPGeoUpdateCommentResponse: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPGeoUpdateCommentResponse> {
        var mergedArray = Array<IGPGeoUpdateCommentResponse>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPGeoUpdateCommentResponse? {
        return try IGPGeoUpdateCommentResponse.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder().mergeFrom(data: data, extensionRegistry:GeoUpdateCommentRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdateCommentResponse {
        return try IGPGeoUpdateCommentResponse.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpResponse": return self.igpResponse
        case "igpComment": return self.igpComment
        default: return nil
        }
    }
}
extension IGPGeoUpdateCommentResponse.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = IGPGeoUpdateCommentResponse
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpResponse": return self.igpResponse
            case "igpComment": return self.igpComment
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpResponse":
                guard let newSubscriptValue = newSubscriptValue as? IGPResponse else {
                    return
                }
                self.igpResponse = newSubscriptValue
            case "igpComment":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpComment = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
