/// Generated by the Protocol Buffers 3.4.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 3.0.22
/// Source file "GeoUpdatePosition.proto"
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct GeoUpdatePositionRoot {
    public static let `default` = GeoUpdatePositionRoot()
    public var extensionRegistry:ExtensionRegistry

    init() {
        extensionRegistry = ExtensionRegistry()
        registerAllExtensions(registry: extensionRegistry)
        RequestRoot.default.registerAllExtensions(registry: extensionRegistry)
        ResponseRoot.default.registerAllExtensions(registry: extensionRegistry)
    }
    public func registerAllExtensions(registry: ExtensionRegistry) {
    }
}

final public class IGPGeoUpdatePosition : GeneratedMessage {
    public typealias BuilderType = IGPGeoUpdatePosition.Builder

    public static func == (lhs: IGPGeoUpdatePosition, rhs: IGPGeoUpdatePosition) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpRequest == rhs.hasIgpRequest) && (!lhs.hasIgpRequest || lhs.igpRequest == rhs.igpRequest)
        fieldCheck = fieldCheck && (lhs.hasIgpLat == rhs.hasIgpLat) && (!lhs.hasIgpLat || lhs.igpLat == rhs.igpLat)
        fieldCheck = fieldCheck && (lhs.hasIgpLon == rhs.hasIgpLon) && (!lhs.hasIgpLon || lhs.igpLon == rhs.igpLon)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpRequest:IGPRequest!
    public fileprivate(set) var hasIgpRequest:Bool = false
    public fileprivate(set) var igpLat:Double! = nil
    public fileprivate(set) var hasIgpLat:Bool = false

    public fileprivate(set) var igpLon:Double! = nil
    public fileprivate(set) var hasIgpLon:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpRequest {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpRequest)
        }
        if hasIgpLat {
            try codedOutputStream.writeDouble(fieldNumber: 2, value:igpLat)
        }
        if hasIgpLon {
            try codedOutputStream.writeDouble(fieldNumber: 3, value:igpLon)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpRequest {
            if let varSizeigpRequest = igpRequest?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpRequest
            }
        }
        if hasIgpLat {
            serialize_size += igpLat.computeDoubleSize(fieldNumber: 2)
        }
        if hasIgpLon {
            serialize_size += igpLon.computeDoubleSize(fieldNumber: 3)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPGeoUpdatePosition.Builder {
        return IGPGeoUpdatePosition.classBuilder() as! IGPGeoUpdatePosition.Builder
    }
    public func getBuilder() -> IGPGeoUpdatePosition.Builder {
        return classBuilder() as! IGPGeoUpdatePosition.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdatePosition.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdatePosition.Builder()
    }
    public func toBuilder() throws -> IGPGeoUpdatePosition.Builder {
        return try IGPGeoUpdatePosition.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPGeoUpdatePosition) throws -> IGPGeoUpdatePosition.Builder {
        return try IGPGeoUpdatePosition.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpRequest {
            jsonMap["IGPRequest"] = try igpRequest.encode()
        }
        if hasIgpLat {
            jsonMap["IGPLat"] = Double(igpLat)
        }
        if hasIgpLon {
            jsonMap["IGPLon"] = Double(igpLon)
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpRequest {
            output += "\(indent) igpRequest {\n"
            if let outDescIgpRequest = igpRequest {
                output += try outDescIgpRequest.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpLat {
            output += "\(indent) igpLat: \(igpLat) \n"
        }
        if hasIgpLon {
            output += "\(indent) igpLon: \(igpLon) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpRequest {
                if let hashValueigpRequest = igpRequest?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpRequest
                }
            }
            if hasIgpLat {
                hashCode = (hashCode &* 31) &+ igpLat.hashValue
            }
            if hasIgpLon {
                hashCode = (hashCode &* 31) &+ igpLon.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPGeoUpdatePosition"
    }
    override public func className() -> String {
        return "IGPGeoUpdatePosition"
    }
    //Meta information declaration end

    final public class Builder : GeneratedRequestMessageBuilder {
        fileprivate var builderResult:IGPGeoUpdatePosition = IGPGeoUpdatePosition()
        public func getMessage() -> IGPGeoUpdatePosition {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpRequest:IGPRequest! {
            get {
                if igpRequestBuilder_ != nil {
                    builderResult.igpRequest = igpRequestBuilder_.getMessage()
                }
                return builderResult.igpRequest
            }
            set (value) {
                builderResult.hasIgpRequest = true
                builderResult.igpRequest = value
            }
        }
        public var hasIgpRequest:Bool {
            get {
                return builderResult.hasIgpRequest
            }
        }
        fileprivate var igpRequestBuilder_:IGPRequest.Builder! {
            didSet {
                builderResult.hasIgpRequest = true
            }
        }
        public func getIgpRequestBuilder() -> IGPRequest.Builder {
            if igpRequestBuilder_ == nil {
                igpRequestBuilder_ = IGPRequest.Builder()
                builderResult.igpRequest = igpRequestBuilder_.getMessage()
                if igpRequest != nil {
                    try! igpRequestBuilder_.mergeFrom(other: igpRequest)
                }
            }
            return igpRequestBuilder_
        }
        @discardableResult
        public override func setIgpRequest(_ value:IGPRequest!) -> IGPGeoUpdatePosition.Builder {
            self.igpRequest = value
            return self
        }
        @discardableResult
        public func mergeIgpRequest(value:IGPRequest) throws -> IGPGeoUpdatePosition.Builder {
            if builderResult.hasIgpRequest {
                builderResult.igpRequest = try IGPRequest.builderWithPrototype(prototype:builderResult.igpRequest).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpRequest = value
            }
            builderResult.hasIgpRequest = true
            return self
        }
        @discardableResult
        public func clearIgpRequest() -> IGPGeoUpdatePosition.Builder {
            igpRequestBuilder_ = nil
            builderResult.hasIgpRequest = false
            builderResult.igpRequest = nil
            return self
        }
        public var igpLat:Double {
            get {
                return builderResult.igpLat
            }
            set (value) {
                builderResult.hasIgpLat = true
                builderResult.igpLat = value
            }
        }
        public var hasIgpLat:Bool {
            get {
                return builderResult.hasIgpLat
            }
        }
        @discardableResult
        public func setIgpLat(_ value:Double) -> IGPGeoUpdatePosition.Builder {
            self.igpLat = value
            return self
        }
        @discardableResult
        public func clearIgpLat() -> IGPGeoUpdatePosition.Builder{
            builderResult.hasIgpLat = false
            builderResult.igpLat = nil
            return self
        }
        public var igpLon:Double {
            get {
                return builderResult.igpLon
            }
            set (value) {
                builderResult.hasIgpLon = true
                builderResult.igpLon = value
            }
        }
        public var hasIgpLon:Bool {
            get {
                return builderResult.hasIgpLon
            }
        }
        @discardableResult
        public func setIgpLon(_ value:Double) -> IGPGeoUpdatePosition.Builder {
            self.igpLon = value
            return self
        }
        @discardableResult
        public func clearIgpLon() -> IGPGeoUpdatePosition.Builder{
            builderResult.hasIgpLon = false
            builderResult.igpLon = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPGeoUpdatePosition.Builder {
            builderResult = IGPGeoUpdatePosition()
            return self
        }
        override public func clone() throws -> IGPGeoUpdatePosition.Builder {
            return try IGPGeoUpdatePosition.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPGeoUpdatePosition {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPGeoUpdatePosition {
            let returnMe:IGPGeoUpdatePosition = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPGeoUpdatePosition) throws -> IGPGeoUpdatePosition.Builder {
            if other == IGPGeoUpdatePosition() {
                return self
            }
            if (other.hasIgpRequest) {
                try mergeIgpRequest(value: other.igpRequest)
            }
            if other.hasIgpLat {
                igpLat = other.igpLat
            }
            if other.hasIgpLon {
                igpLon = other.igpLon
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdatePosition.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePosition.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPRequest.Builder = IGPRequest.Builder()
                    if hasIgpRequest {
                        try subBuilder.mergeFrom(other: igpRequest)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpRequest = subBuilder.buildPartial()

                case 17:
                    igpLat = try codedInputStream.readDouble()

                case 25:
                    igpLon = try codedInputStream.readDouble()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdatePosition.Builder {
            let resultDecodedBuilder = IGPGeoUpdatePosition.Builder()
            if let jsonValueIgpRequest = jsonMap["IGPRequest"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpRequest = try IGPRequest.Builder.decodeToBuilder(jsonMap:jsonValueIgpRequest).build()

            }
            if let jsonValueIgpLat = jsonMap["IGPLat"] as? Double {
                resultDecodedBuilder.igpLat = Double(jsonValueIgpLat)
            } else if let jsonValueIgpLat = jsonMap["IGPLat"] as? String {
                resultDecodedBuilder.igpLat = Double(jsonValueIgpLat)!
            }
            if let jsonValueIgpLon = jsonMap["IGPLon"] as? Double {
                resultDecodedBuilder.igpLon = Double(jsonValueIgpLon)
            } else if let jsonValueIgpLon = jsonMap["IGPLon"] as? String {
                resultDecodedBuilder.igpLon = Double(jsonValueIgpLon)!
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPGeoUpdatePosition.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPGeoUpdatePosition.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

final public class IGPGeoUpdatePositionResponse : GeneratedResponseMessage {
    public typealias BuilderType = IGPGeoUpdatePositionResponse.Builder

    public static func == (lhs: IGPGeoUpdatePositionResponse, rhs: IGPGeoUpdatePositionResponse) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpResponse == rhs.hasIgpResponse) && (!lhs.hasIgpResponse || lhs.igpResponse == rhs.igpResponse)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpResponse {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpResponse)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpResponse {
            if let varSizeigpResponse = igpResponse?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpResponse
            }
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPGeoUpdatePositionResponse.Builder {
        return IGPGeoUpdatePositionResponse.classBuilder() as! IGPGeoUpdatePositionResponse.Builder
    }
    public func getBuilder() -> IGPGeoUpdatePositionResponse.Builder {
        return classBuilder() as! IGPGeoUpdatePositionResponse.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdatePositionResponse.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPGeoUpdatePositionResponse.Builder()
    }
    public func toBuilder() throws -> IGPGeoUpdatePositionResponse.Builder {
        return try IGPGeoUpdatePositionResponse.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPGeoUpdatePositionResponse) throws -> IGPGeoUpdatePositionResponse.Builder {
        return try IGPGeoUpdatePositionResponse.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpResponse {
            jsonMap["IGPResponse"] = try igpResponse.encode()
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpResponse {
            output += "\(indent) igpResponse {\n"
            if let outDescIgpResponse = igpResponse {
                output += try outDescIgpResponse.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpResponse {
                if let hashValueigpResponse = igpResponse?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpResponse
                }
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPGeoUpdatePositionResponse"
    }
    override public func className() -> String {
        return "IGPGeoUpdatePositionResponse"
    }
    //Meta information declaration end

    final public class Builder : GeneratedResponseMessageBuilder {
        fileprivate var builderResult:IGPGeoUpdatePositionResponse = IGPGeoUpdatePositionResponse()
        public func getMessage() -> IGPGeoUpdatePositionResponse {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpResponse:IGPResponse! {
            get {
                if igpResponseBuilder_ != nil {
                    builderResult.igpResponse = igpResponseBuilder_.getMessage()
                }
                return builderResult.igpResponse
            }
            set (value) {
                builderResult.hasIgpResponse = true
                builderResult.igpResponse = value
            }
        }
        public var hasIgpResponse:Bool {
            get {
                return builderResult.hasIgpResponse
            }
        }
        fileprivate var igpResponseBuilder_:IGPResponse.Builder! {
            didSet {
                builderResult.hasIgpResponse = true
            }
        }
        public func getIgpResponseBuilder() -> IGPResponse.Builder {
            if igpResponseBuilder_ == nil {
                igpResponseBuilder_ = IGPResponse.Builder()
                builderResult.igpResponse = igpResponseBuilder_.getMessage()
                if igpResponse != nil {
                    try! igpResponseBuilder_.mergeFrom(other: igpResponse)
                }
            }
            return igpResponseBuilder_
        }
        @discardableResult
        public func setIgpResponse(_ value:IGPResponse!) -> IGPGeoUpdatePositionResponse.Builder {
            self.igpResponse = value
            return self
        }
        @discardableResult
        public func mergeIgpResponse(value:IGPResponse) throws -> IGPGeoUpdatePositionResponse.Builder {
            if builderResult.hasIgpResponse {
                builderResult.igpResponse = try IGPResponse.builderWithPrototype(prototype:builderResult.igpResponse).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpResponse = value
            }
            builderResult.hasIgpResponse = true
            return self
        }
        @discardableResult
        public func clearIgpResponse() -> IGPGeoUpdatePositionResponse.Builder {
            igpResponseBuilder_ = nil
            builderResult.hasIgpResponse = false
            builderResult.igpResponse = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPGeoUpdatePositionResponse.Builder {
            builderResult = IGPGeoUpdatePositionResponse()
            return self
        }
        override public func clone() throws -> IGPGeoUpdatePositionResponse.Builder {
            return try IGPGeoUpdatePositionResponse.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPGeoUpdatePositionResponse {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPGeoUpdatePositionResponse {
            let returnMe:IGPGeoUpdatePositionResponse = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPGeoUpdatePositionResponse) throws -> IGPGeoUpdatePositionResponse.Builder {
            if other == IGPGeoUpdatePositionResponse() {
                return self
            }
            if (other.hasIgpResponse) {
                try mergeIgpResponse(value: other.igpResponse)
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdatePositionResponse.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePositionResponse.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPResponse.Builder = IGPResponse.Builder()
                    if hasIgpResponse {
                        try subBuilder.mergeFrom(other: igpResponse)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpResponse = subBuilder.buildPartial()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPGeoUpdatePositionResponse.Builder {
            let resultDecodedBuilder = IGPGeoUpdatePositionResponse.Builder()
            if let jsonValueIgpResponse = jsonMap["IGPResponse"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpResponse = try IGPResponse.Builder.decodeToBuilder(jsonMap:jsonValueIgpResponse).build()

            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPGeoUpdatePositionResponse.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPGeoUpdatePositionResponse.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

extension IGPGeoUpdatePosition: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPGeoUpdatePosition> {
        var mergedArray = Array<IGPGeoUpdatePosition>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPGeoUpdatePosition? {
        return try IGPGeoUpdatePosition.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder().mergeFrom(data: data, extensionRegistry:GeoUpdatePositionRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePosition {
        return try IGPGeoUpdatePosition.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpRequest": return self.igpRequest
        case "igpLat": return self.igpLat
        case "igpLon": return self.igpLon
        default: return nil
        }
    }
}
extension IGPGeoUpdatePosition.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = IGPGeoUpdatePosition
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpRequest": return self.igpRequest
            case "igpLat": return self.igpLat
            case "igpLon": return self.igpLon
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpRequest":
                guard let newSubscriptValue = newSubscriptValue as? IGPRequest else {
                    return
                }
                self.igpRequest = newSubscriptValue
            case "igpLat":
                guard let newSubscriptValue = newSubscriptValue as? Double else {
                    return
                }
                self.igpLat = newSubscriptValue
            case "igpLon":
                guard let newSubscriptValue = newSubscriptValue as? Double else {
                    return
                }
                self.igpLon = newSubscriptValue
            default: return
            }
        }
    }
}
extension IGPGeoUpdatePositionResponse: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPGeoUpdatePositionResponse> {
        var mergedArray = Array<IGPGeoUpdatePositionResponse>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPGeoUpdatePositionResponse? {
        return try IGPGeoUpdatePositionResponse.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder().mergeFrom(data: data, extensionRegistry:GeoUpdatePositionRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPGeoUpdatePositionResponse {
        return try IGPGeoUpdatePositionResponse.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpResponse": return self.igpResponse
        default: return nil
        }
    }
}
extension IGPGeoUpdatePositionResponse.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = IGPGeoUpdatePositionResponse
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpResponse": return self.igpResponse
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpResponse":
                guard let newSubscriptValue = newSubscriptValue as? IGPResponse else {
                    return
                }
                self.igpResponse = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
