/// Generated by the Protocol Buffers 3.4.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 3.0.22
/// Source file "UserContactsEdit.proto"
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct UserContactsEditRoot {
    public static let `default` = UserContactsEditRoot()
    public var extensionRegistry:ExtensionRegistry

    init() {
        extensionRegistry = ExtensionRegistry()
        registerAllExtensions(registry: extensionRegistry)
        RequestRoot.default.registerAllExtensions(registry: extensionRegistry)
        ResponseRoot.default.registerAllExtensions(registry: extensionRegistry)
    }
    public func registerAllExtensions(registry: ExtensionRegistry) {
    }
}

final public class IGPUserContactsEdit : GeneratedMessage {
    public typealias BuilderType = IGPUserContactsEdit.Builder

    public static func == (lhs: IGPUserContactsEdit, rhs: IGPUserContactsEdit) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpRequest == rhs.hasIgpRequest) && (!lhs.hasIgpRequest || lhs.igpRequest == rhs.igpRequest)
        fieldCheck = fieldCheck && (lhs.hasIgpPhone == rhs.hasIgpPhone) && (!lhs.hasIgpPhone || lhs.igpPhone == rhs.igpPhone)
        fieldCheck = fieldCheck && (lhs.hasIgpFirstName == rhs.hasIgpFirstName) && (!lhs.hasIgpFirstName || lhs.igpFirstName == rhs.igpFirstName)
        fieldCheck = fieldCheck && (lhs.hasIgpLastName == rhs.hasIgpLastName) && (!lhs.hasIgpLastName || lhs.igpLastName == rhs.igpLastName)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpRequest:IGPRequest!
    public fileprivate(set) var hasIgpRequest:Bool = false
    public fileprivate(set) var igpPhone:Int64! = nil
    public fileprivate(set) var hasIgpPhone:Bool = false

    public fileprivate(set) var igpFirstName:String! = nil
    public fileprivate(set) var hasIgpFirstName:Bool = false

    public fileprivate(set) var igpLastName:String! = nil
    public fileprivate(set) var hasIgpLastName:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpRequest {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpRequest)
        }
        if hasIgpPhone {
            try codedOutputStream.writeInt64(fieldNumber: 2, value:igpPhone)
        }
        if hasIgpFirstName {
            try codedOutputStream.writeString(fieldNumber: 3, value:igpFirstName)
        }
        if hasIgpLastName {
            try codedOutputStream.writeString(fieldNumber: 4, value:igpLastName)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpRequest {
            if let varSizeigpRequest = igpRequest?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpRequest
            }
        }
        if hasIgpPhone {
            serialize_size += igpPhone.computeInt64Size(fieldNumber: 2)
        }
        if hasIgpFirstName {
            serialize_size += igpFirstName.computeStringSize(fieldNumber: 3)
        }
        if hasIgpLastName {
            serialize_size += igpLastName.computeStringSize(fieldNumber: 4)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPUserContactsEdit.Builder {
        return IGPUserContactsEdit.classBuilder() as! IGPUserContactsEdit.Builder
    }
    public func getBuilder() -> IGPUserContactsEdit.Builder {
        return classBuilder() as! IGPUserContactsEdit.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPUserContactsEdit.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPUserContactsEdit.Builder()
    }
    public func toBuilder() throws -> IGPUserContactsEdit.Builder {
        return try IGPUserContactsEdit.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPUserContactsEdit) throws -> IGPUserContactsEdit.Builder {
        return try IGPUserContactsEdit.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpRequest {
            jsonMap["IGPRequest"] = try igpRequest.encode()
        }
        if hasIgpPhone {
            jsonMap["IGPPhone"] = "\(igpPhone!)"
        }
        if hasIgpFirstName {
            jsonMap["IGPFirstName"] = igpFirstName
        }
        if hasIgpLastName {
            jsonMap["IGPLastName"] = igpLastName
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpRequest {
            output += "\(indent) igpRequest {\n"
            if let outDescIgpRequest = igpRequest {
                output += try outDescIgpRequest.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpPhone {
            output += "\(indent) igpPhone: \(igpPhone) \n"
        }
        if hasIgpFirstName {
            output += "\(indent) igpFirstName: \(igpFirstName) \n"
        }
        if hasIgpLastName {
            output += "\(indent) igpLastName: \(igpLastName) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpRequest {
                if let hashValueigpRequest = igpRequest?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpRequest
                }
            }
            if hasIgpPhone {
                hashCode = (hashCode &* 31) &+ igpPhone.hashValue
            }
            if hasIgpFirstName {
                hashCode = (hashCode &* 31) &+ igpFirstName.hashValue
            }
            if hasIgpLastName {
                hashCode = (hashCode &* 31) &+ igpLastName.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPUserContactsEdit"
    }
    override public func className() -> String {
        return "IGPUserContactsEdit"
    }
    //Meta information declaration end

    final public class Builder : GeneratedRequestMessageBuilder {
        fileprivate var builderResult:IGPUserContactsEdit = IGPUserContactsEdit()
        public func getMessage() -> IGPUserContactsEdit {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpRequest:IGPRequest! {
            get {
                if igpRequestBuilder_ != nil {
                    builderResult.igpRequest = igpRequestBuilder_.getMessage()
                }
                return builderResult.igpRequest
            }
            set (value) {
                builderResult.hasIgpRequest = true
                builderResult.igpRequest = value
            }
        }
        public var hasIgpRequest:Bool {
            get {
                return builderResult.hasIgpRequest
            }
        }
        fileprivate var igpRequestBuilder_:IGPRequest.Builder! {
            didSet {
                builderResult.hasIgpRequest = true
            }
        }
        public func getIgpRequestBuilder() -> IGPRequest.Builder {
            if igpRequestBuilder_ == nil {
                igpRequestBuilder_ = IGPRequest.Builder()
                builderResult.igpRequest = igpRequestBuilder_.getMessage()
                if igpRequest != nil {
                    try! igpRequestBuilder_.mergeFrom(other: igpRequest)
                }
            }
            return igpRequestBuilder_
        }
        @discardableResult
        public override func setIgpRequest(_ value:IGPRequest!) -> IGPUserContactsEdit.Builder {
            self.igpRequest = value
            return self
        }
        @discardableResult
        public func mergeIgpRequest(value:IGPRequest) throws -> IGPUserContactsEdit.Builder {
            if builderResult.hasIgpRequest {
                builderResult.igpRequest = try IGPRequest.builderWithPrototype(prototype:builderResult.igpRequest).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpRequest = value
            }
            builderResult.hasIgpRequest = true
            return self
        }
        @discardableResult
        public func clearIgpRequest() -> IGPUserContactsEdit.Builder {
            igpRequestBuilder_ = nil
            builderResult.hasIgpRequest = false
            builderResult.igpRequest = nil
            return self
        }
        public var igpPhone:Int64 {
            get {
                return builderResult.igpPhone
            }
            set (value) {
                builderResult.hasIgpPhone = true
                builderResult.igpPhone = value
            }
        }
        public var hasIgpPhone:Bool {
            get {
                return builderResult.hasIgpPhone
            }
        }
        @discardableResult
        public func setIgpPhone(_ value:Int64) -> IGPUserContactsEdit.Builder {
            self.igpPhone = value
            return self
        }
        @discardableResult
        public func clearIgpPhone() -> IGPUserContactsEdit.Builder{
            builderResult.hasIgpPhone = false
            builderResult.igpPhone = nil
            return self
        }
        public var igpFirstName:String {
            get {
                return builderResult.igpFirstName
            }
            set (value) {
                builderResult.hasIgpFirstName = true
                builderResult.igpFirstName = value
            }
        }
        public var hasIgpFirstName:Bool {
            get {
                return builderResult.hasIgpFirstName
            }
        }
        @discardableResult
        public func setIgpFirstName(_ value:String) -> IGPUserContactsEdit.Builder {
            self.igpFirstName = value
            return self
        }
        @discardableResult
        public func clearIgpFirstName() -> IGPUserContactsEdit.Builder{
            builderResult.hasIgpFirstName = false
            builderResult.igpFirstName = nil
            return self
        }
        public var igpLastName:String {
            get {
                return builderResult.igpLastName
            }
            set (value) {
                builderResult.hasIgpLastName = true
                builderResult.igpLastName = value
            }
        }
        public var hasIgpLastName:Bool {
            get {
                return builderResult.hasIgpLastName
            }
        }
        @discardableResult
        public func setIgpLastName(_ value:String) -> IGPUserContactsEdit.Builder {
            self.igpLastName = value
            return self
        }
        @discardableResult
        public func clearIgpLastName() -> IGPUserContactsEdit.Builder{
            builderResult.hasIgpLastName = false
            builderResult.igpLastName = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPUserContactsEdit.Builder {
            builderResult = IGPUserContactsEdit()
            return self
        }
        override public func clone() throws -> IGPUserContactsEdit.Builder {
            return try IGPUserContactsEdit.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPUserContactsEdit {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPUserContactsEdit {
            let returnMe:IGPUserContactsEdit = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPUserContactsEdit) throws -> IGPUserContactsEdit.Builder {
            if other == IGPUserContactsEdit() {
                return self
            }
            if (other.hasIgpRequest) {
                try mergeIgpRequest(value: other.igpRequest)
            }
            if other.hasIgpPhone {
                igpPhone = other.igpPhone
            }
            if other.hasIgpFirstName {
                igpFirstName = other.igpFirstName
            }
            if other.hasIgpLastName {
                igpLastName = other.igpLastName
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPUserContactsEdit.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEdit.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPRequest.Builder = IGPRequest.Builder()
                    if hasIgpRequest {
                        try subBuilder.mergeFrom(other: igpRequest)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpRequest = subBuilder.buildPartial()

                case 16:
                    igpPhone = try codedInputStream.readInt64()

                case 26:
                    igpFirstName = try codedInputStream.readString()

                case 34:
                    igpLastName = try codedInputStream.readString()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPUserContactsEdit.Builder {
            let resultDecodedBuilder = IGPUserContactsEdit.Builder()
            if let jsonValueIgpRequest = jsonMap["IGPRequest"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpRequest = try IGPRequest.Builder.decodeToBuilder(jsonMap:jsonValueIgpRequest).build()

            }
            if let jsonValueIgpPhone = jsonMap["IGPPhone"] as? String {
                resultDecodedBuilder.igpPhone = Int64(jsonValueIgpPhone)!
            } else if let jsonValueIgpPhone = jsonMap["IGPPhone"] as? Int {
                resultDecodedBuilder.igpPhone = Int64(jsonValueIgpPhone)
            }
            if let jsonValueIgpFirstName = jsonMap["IGPFirstName"] as? String {
                resultDecodedBuilder.igpFirstName = jsonValueIgpFirstName
            }
            if let jsonValueIgpLastName = jsonMap["IGPLastName"] as? String {
                resultDecodedBuilder.igpLastName = jsonValueIgpLastName
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPUserContactsEdit.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPUserContactsEdit.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

final public class IGPUserContactsEditResponse : GeneratedResponseMessage {
    public typealias BuilderType = IGPUserContactsEditResponse.Builder

    public static func == (lhs: IGPUserContactsEditResponse, rhs: IGPUserContactsEditResponse) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasIgpResponse == rhs.hasIgpResponse) && (!lhs.hasIgpResponse || lhs.igpResponse == rhs.igpResponse)
        fieldCheck = fieldCheck && (lhs.hasIgpPhone == rhs.hasIgpPhone) && (!lhs.hasIgpPhone || lhs.igpPhone == rhs.igpPhone)
        fieldCheck = fieldCheck && (lhs.hasIgpFirstName == rhs.hasIgpFirstName) && (!lhs.hasIgpFirstName || lhs.igpFirstName == rhs.igpFirstName)
        fieldCheck = fieldCheck && (lhs.hasIgpLastName == rhs.hasIgpLastName) && (!lhs.hasIgpLastName || lhs.igpLastName == rhs.igpLastName)
        fieldCheck = fieldCheck && (lhs.hasIgpInitials == rhs.hasIgpInitials) && (!lhs.hasIgpInitials || lhs.igpInitials == rhs.igpInitials)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }



    //iGap Properties declaration start



    //iGap Properties declaration end

    public fileprivate(set) var igpPhone:Int64! = nil
    public fileprivate(set) var hasIgpPhone:Bool = false

    public fileprivate(set) var igpFirstName:String! = nil
    public fileprivate(set) var hasIgpFirstName:Bool = false

    public fileprivate(set) var igpLastName:String! = nil
    public fileprivate(set) var hasIgpLastName:Bool = false

    public fileprivate(set) var igpInitials:String! = nil
    public fileprivate(set) var hasIgpInitials:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasIgpResponse {
            try codedOutputStream.writeMessage(fieldNumber: 1, value:igpResponse)
        }
        if hasIgpPhone {
            try codedOutputStream.writeInt64(fieldNumber: 2, value:igpPhone)
        }
        if hasIgpFirstName {
            try codedOutputStream.writeString(fieldNumber: 3, value:igpFirstName)
        }
        if hasIgpLastName {
            try codedOutputStream.writeString(fieldNumber: 4, value:igpLastName)
        }
        if hasIgpInitials {
            try codedOutputStream.writeString(fieldNumber: 5, value:igpInitials)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasIgpResponse {
            if let varSizeigpResponse = igpResponse?.computeMessageSize(fieldNumber: 1) {
                serialize_size += varSizeigpResponse
            }
        }
        if hasIgpPhone {
            serialize_size += igpPhone.computeInt64Size(fieldNumber: 2)
        }
        if hasIgpFirstName {
            serialize_size += igpFirstName.computeStringSize(fieldNumber: 3)
        }
        if hasIgpLastName {
            serialize_size += igpLastName.computeStringSize(fieldNumber: 4)
        }
        if hasIgpInitials {
            serialize_size += igpInitials.computeStringSize(fieldNumber: 5)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> IGPUserContactsEditResponse.Builder {
        return IGPUserContactsEditResponse.classBuilder() as! IGPUserContactsEditResponse.Builder
    }
    public func getBuilder() -> IGPUserContactsEditResponse.Builder {
        return classBuilder() as! IGPUserContactsEditResponse.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPUserContactsEditResponse.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return IGPUserContactsEditResponse.Builder()
    }
    public func toBuilder() throws -> IGPUserContactsEditResponse.Builder {
        return try IGPUserContactsEditResponse.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:IGPUserContactsEditResponse) throws -> IGPUserContactsEditResponse.Builder {
        return try IGPUserContactsEditResponse.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasIgpResponse {
            jsonMap["IGPResponse"] = try igpResponse.encode()
        }
        if hasIgpPhone {
            jsonMap["IGPPhone"] = "\(igpPhone!)"
        }
        if hasIgpFirstName {
            jsonMap["IGPFirstName"] = igpFirstName
        }
        if hasIgpLastName {
            jsonMap["IGPLastName"] = igpLastName
        }
        if hasIgpInitials {
            jsonMap["IGPInitials"] = igpInitials
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasIgpResponse {
            output += "\(indent) igpResponse {\n"
            if let outDescIgpResponse = igpResponse {
                output += try outDescIgpResponse.getDescription(indent: "\(indent)  ")
            }
            output += "\(indent) }\n"
        }
        if hasIgpPhone {
            output += "\(indent) igpPhone: \(igpPhone) \n"
        }
        if hasIgpFirstName {
            output += "\(indent) igpFirstName: \(igpFirstName) \n"
        }
        if hasIgpLastName {
            output += "\(indent) igpLastName: \(igpLastName) \n"
        }
        if hasIgpInitials {
            output += "\(indent) igpInitials: \(igpInitials) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasIgpResponse {
                if let hashValueigpResponse = igpResponse?.hashValue {
                    hashCode = (hashCode &* 31) &+ hashValueigpResponse
                }
            }
            if hasIgpPhone {
                hashCode = (hashCode &* 31) &+ igpPhone.hashValue
            }
            if hasIgpFirstName {
                hashCode = (hashCode &* 31) &+ igpFirstName.hashValue
            }
            if hasIgpLastName {
                hashCode = (hashCode &* 31) &+ igpLastName.hashValue
            }
            if hasIgpInitials {
                hashCode = (hashCode &* 31) &+ igpInitials.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "IGPUserContactsEditResponse"
    }
    override public func className() -> String {
        return "IGPUserContactsEditResponse"
    }
    //Meta information declaration end

    final public class Builder : GeneratedResponseMessageBuilder {
        fileprivate var builderResult:IGPUserContactsEditResponse = IGPUserContactsEditResponse()
        public func getMessage() -> IGPUserContactsEditResponse {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var igpResponse:IGPResponse! {
            get {
                if igpResponseBuilder_ != nil {
                    builderResult.igpResponse = igpResponseBuilder_.getMessage()
                }
                return builderResult.igpResponse
            }
            set (value) {
                builderResult.hasIgpResponse = true
                builderResult.igpResponse = value
            }
        }
        public var hasIgpResponse:Bool {
            get {
                return builderResult.hasIgpResponse
            }
        }
        fileprivate var igpResponseBuilder_:IGPResponse.Builder! {
            didSet {
                builderResult.hasIgpResponse = true
            }
        }
        public func getIgpResponseBuilder() -> IGPResponse.Builder {
            if igpResponseBuilder_ == nil {
                igpResponseBuilder_ = IGPResponse.Builder()
                builderResult.igpResponse = igpResponseBuilder_.getMessage()
                if igpResponse != nil {
                    try! igpResponseBuilder_.mergeFrom(other: igpResponse)
                }
            }
            return igpResponseBuilder_
        }
        @discardableResult
        public func setIgpResponse(_ value:IGPResponse!) -> IGPUserContactsEditResponse.Builder {
            self.igpResponse = value
            return self
        }
        @discardableResult
        public func mergeIgpResponse(value:IGPResponse) throws -> IGPUserContactsEditResponse.Builder {
            if builderResult.hasIgpResponse {
                builderResult.igpResponse = try IGPResponse.builderWithPrototype(prototype:builderResult.igpResponse).mergeFrom(other: value).buildPartial()
            } else {
                builderResult.igpResponse = value
            }
            builderResult.hasIgpResponse = true
            return self
        }
        @discardableResult
        public func clearIgpResponse() -> IGPUserContactsEditResponse.Builder {
            igpResponseBuilder_ = nil
            builderResult.hasIgpResponse = false
            builderResult.igpResponse = nil
            return self
        }
        public var igpPhone:Int64 {
            get {
                return builderResult.igpPhone
            }
            set (value) {
                builderResult.hasIgpPhone = true
                builderResult.igpPhone = value
            }
        }
        public var hasIgpPhone:Bool {
            get {
                return builderResult.hasIgpPhone
            }
        }
        @discardableResult
        public func setIgpPhone(_ value:Int64) -> IGPUserContactsEditResponse.Builder {
            self.igpPhone = value
            return self
        }
        @discardableResult
        public func clearIgpPhone() -> IGPUserContactsEditResponse.Builder{
            builderResult.hasIgpPhone = false
            builderResult.igpPhone = nil
            return self
        }
        public var igpFirstName:String {
            get {
                return builderResult.igpFirstName
            }
            set (value) {
                builderResult.hasIgpFirstName = true
                builderResult.igpFirstName = value
            }
        }
        public var hasIgpFirstName:Bool {
            get {
                return builderResult.hasIgpFirstName
            }
        }
        @discardableResult
        public func setIgpFirstName(_ value:String) -> IGPUserContactsEditResponse.Builder {
            self.igpFirstName = value
            return self
        }
        @discardableResult
        public func clearIgpFirstName() -> IGPUserContactsEditResponse.Builder{
            builderResult.hasIgpFirstName = false
            builderResult.igpFirstName = nil
            return self
        }
        public var igpLastName:String {
            get {
                return builderResult.igpLastName
            }
            set (value) {
                builderResult.hasIgpLastName = true
                builderResult.igpLastName = value
            }
        }
        public var hasIgpLastName:Bool {
            get {
                return builderResult.hasIgpLastName
            }
        }
        @discardableResult
        public func setIgpLastName(_ value:String) -> IGPUserContactsEditResponse.Builder {
            self.igpLastName = value
            return self
        }
        @discardableResult
        public func clearIgpLastName() -> IGPUserContactsEditResponse.Builder{
            builderResult.hasIgpLastName = false
            builderResult.igpLastName = nil
            return self
        }
        public var igpInitials:String {
            get {
                return builderResult.igpInitials
            }
            set (value) {
                builderResult.hasIgpInitials = true
                builderResult.igpInitials = value
            }
        }
        public var hasIgpInitials:Bool {
            get {
                return builderResult.hasIgpInitials
            }
        }
        @discardableResult
        public func setIgpInitials(_ value:String) -> IGPUserContactsEditResponse.Builder {
            self.igpInitials = value
            return self
        }
        @discardableResult
        public func clearIgpInitials() -> IGPUserContactsEditResponse.Builder{
            builderResult.hasIgpInitials = false
            builderResult.igpInitials = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> IGPUserContactsEditResponse.Builder {
            builderResult = IGPUserContactsEditResponse()
            return self
        }
        override public func clone() throws -> IGPUserContactsEditResponse.Builder {
            return try IGPUserContactsEditResponse.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> IGPUserContactsEditResponse {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> IGPUserContactsEditResponse {
            let returnMe:IGPUserContactsEditResponse = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:IGPUserContactsEditResponse) throws -> IGPUserContactsEditResponse.Builder {
            if other == IGPUserContactsEditResponse() {
                return self
            }
            if (other.hasIgpResponse) {
                try mergeIgpResponse(value: other.igpResponse)
            }
            if other.hasIgpPhone {
                igpPhone = other.igpPhone
            }
            if other.hasIgpFirstName {
                igpFirstName = other.igpFirstName
            }
            if other.hasIgpLastName {
                igpLastName = other.igpLastName
            }
            if other.hasIgpInitials {
                igpInitials = other.igpInitials
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> IGPUserContactsEditResponse.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEditResponse.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    let subBuilder:IGPResponse.Builder = IGPResponse.Builder()
                    if hasIgpResponse {
                        try subBuilder.mergeFrom(other: igpResponse)
                    }
                    try codedInputStream.readMessage(builder: subBuilder, extensionRegistry:extensionRegistry)
                    igpResponse = subBuilder.buildPartial()

                case 16:
                    igpPhone = try codedInputStream.readInt64()

                case 26:
                    igpFirstName = try codedInputStream.readString()

                case 34:
                    igpLastName = try codedInputStream.readString()

                case 42:
                    igpInitials = try codedInputStream.readString()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> IGPUserContactsEditResponse.Builder {
            let resultDecodedBuilder = IGPUserContactsEditResponse.Builder()
            if let jsonValueIgpResponse = jsonMap["IGPResponse"] as? Dictionary<String,Any> {
                resultDecodedBuilder.igpResponse = try IGPResponse.Builder.decodeToBuilder(jsonMap:jsonValueIgpResponse).build()

            }
            if let jsonValueIgpPhone = jsonMap["IGPPhone"] as? String {
                resultDecodedBuilder.igpPhone = Int64(jsonValueIgpPhone)!
            } else if let jsonValueIgpPhone = jsonMap["IGPPhone"] as? Int {
                resultDecodedBuilder.igpPhone = Int64(jsonValueIgpPhone)
            }
            if let jsonValueIgpFirstName = jsonMap["IGPFirstName"] as? String {
                resultDecodedBuilder.igpFirstName = jsonValueIgpFirstName
            }
            if let jsonValueIgpLastName = jsonMap["IGPLastName"] as? String {
                resultDecodedBuilder.igpLastName = jsonValueIgpLastName
            }
            if let jsonValueIgpInitials = jsonMap["IGPInitials"] as? String {
                resultDecodedBuilder.igpInitials = jsonValueIgpInitials
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> IGPUserContactsEditResponse.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try IGPUserContactsEditResponse.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

extension IGPUserContactsEdit: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPUserContactsEdit> {
        var mergedArray = Array<IGPUserContactsEdit>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPUserContactsEdit? {
        return try IGPUserContactsEdit.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder().mergeFrom(data: data, extensionRegistry:UserContactsEditRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEdit {
        return try IGPUserContactsEdit.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpRequest": return self.igpRequest
        case "igpPhone": return self.igpPhone
        case "igpFirstName": return self.igpFirstName
        case "igpLastName": return self.igpLastName
        default: return nil
        }
    }
}
extension IGPUserContactsEdit.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = IGPUserContactsEdit
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpRequest": return self.igpRequest
            case "igpPhone": return self.igpPhone
            case "igpFirstName": return self.igpFirstName
            case "igpLastName": return self.igpLastName
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpRequest":
                guard let newSubscriptValue = newSubscriptValue as? IGPRequest else {
                    return
                }
                self.igpRequest = newSubscriptValue
            case "igpPhone":
                guard let newSubscriptValue = newSubscriptValue as? Int64 else {
                    return
                }
                self.igpPhone = newSubscriptValue
            case "igpFirstName":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpFirstName = newSubscriptValue
            case "igpLastName":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpLastName = newSubscriptValue
            default: return
            }
        }
    }
}
extension IGPUserContactsEditResponse: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<IGPUserContactsEditResponse> {
        var mergedArray = Array<IGPUserContactsEditResponse>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> IGPUserContactsEditResponse? {
        return try IGPUserContactsEditResponse.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder().mergeFrom(data: data, extensionRegistry:UserContactsEditRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> IGPUserContactsEditResponse {
        return try IGPUserContactsEditResponse.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "igpResponse": return self.igpResponse
        case "igpPhone": return self.igpPhone
        case "igpFirstName": return self.igpFirstName
        case "igpLastName": return self.igpLastName
        case "igpInitials": return self.igpInitials
        default: return nil
        }
    }
}
extension IGPUserContactsEditResponse.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = IGPUserContactsEditResponse
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "igpResponse": return self.igpResponse
            case "igpPhone": return self.igpPhone
            case "igpFirstName": return self.igpFirstName
            case "igpLastName": return self.igpLastName
            case "igpInitials": return self.igpInitials
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "igpResponse":
                guard let newSubscriptValue = newSubscriptValue as? IGPResponse else {
                    return
                }
                self.igpResponse = newSubscriptValue
            case "igpPhone":
                guard let newSubscriptValue = newSubscriptValue as? Int64 else {
                    return
                }
                self.igpPhone = newSubscriptValue
            case "igpFirstName":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpFirstName = newSubscriptValue
            case "igpLastName":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpLastName = newSubscriptValue
            case "igpInitials":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.igpInitials = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
